// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Encryption is an autogenerated mock type for the Encryption type
type Encryption struct {
	mock.Mock
}

// EncGetTest provides a mock function with given fields:
func (_m *Encryption) EncGetTest() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
