required:
  - name
  - description
  - permissions
type: object
properties:
  name:
    type: string
  description:
    type: string
  system:
    type: boolean
  permissions:
    type: array
    items:
      type: string
  scopes:
    type: array
    items:
      type: string
