// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Emailer is an autogenerated mock type for the Emailer type
type Emailer struct {
	mock.Mock
}

// Send provides a mock function with given fields: toEmail, subject, body, attachmentFilename
func (_m *Emailer) Send(toEmail string, subject string, body string, attachmentFilename *string) error {
	ret := _m.Called(toEmail, subject, body, attachmentFilename)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, *string) error); ok {
		r0 = rf(toEmail, subject, body, attachmentFilename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEmailer interface {
	mock.TestingT
	Cleanup(func())
}

// NewEmailer creates a new instance of Emailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEmailer(t mockConstructorTestingTNewEmailer) *Emailer {
	mock := &Emailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
