version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-2
    ECR_ACCOUNT_ID: "779619664536"
    ECR_REPOSITORY: "rokwire/coreservice"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      - IMAGE_REPO=${ECR_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY}

      - echo Reading version from VERSION file
      - VERSION=$(cat VERSION)
      - IMAGE_TAG=${VERSION}
      - echo Using VERSION=${VERSION}
      - echo Using IMAGE_TAG=${IMAGE_TAG}

      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

  build:
    commands:
      - echo Building Docker image
      - docker build -t ${IMAGE_REPO}:${IMAGE_TAG} .

  post_build:
    commands:
      - echo Pushing Docker image to ECR
      - docker push ${IMAGE_REPO}:${IMAGE_TAG}
      - echo Build completed

artifacts:
  files:
    - "**/*"
  discard-paths: yes