delete:
  tags:
  - Admin
  summary: Delete roles from account
  description: |
    Deletes an existing roles from account

    **Auth:** Requires admin access token with 'update_account-auth-roles' or `update_account-authorization` permission
  security:
    - bearerAuth: []
  requestBody:
    description: Roles
    content:
      application/json:
        schema:
          $ref: "../../../../../schemas/apis/admin/application/account/roles/revoke/request/Request.yaml"
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error 