// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Listener is an autogenerated mock type for the Listener type
type Listener struct {
	mock.Mock
}

// OnAPIKeysUpdated provides a mock function with given fields:
func (_m *Listener) OnAPIKeysUpdated() {
	_m.Called()
}

// OnApplicationsOrganizationsUpdated provides a mock function with given fields:
func (_m *Listener) OnApplicationsOrganizationsUpdated() {
	_m.Called()
}

// OnApplicationsUpdated provides a mock function with given fields:
func (_m *Listener) OnApplicationsUpdated() {
	_m.Called()
}

// OnAuthTypesUpdated provides a mock function with given fields:
func (_m *Listener) OnAuthTypesUpdated() {
	_m.Called()
}

// OnIdentityProvidersUpdated provides a mock function with given fields:
func (_m *Listener) OnIdentityProvidersUpdated() {
	_m.Called()
}

// OnOrganizationsUpdated provides a mock function with given fields:
func (_m *Listener) OnOrganizationsUpdated() {
	_m.Called()
}

// OnServiceRegsUpdated provides a mock function with given fields:
func (_m *Listener) OnServiceRegsUpdated() {
	_m.Called()
}
