// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	tokenauth "github.com/rokwire/core-auth-library-go/tokenauth"
	mock "github.com/stretchr/testify/mock"
)

// Authorization is an autogenerated mock type for the Authorization type
type Authorization struct {
	mock.Mock
}

// check provides a mock function with given fields: req
func (_m *Authorization) check(req *http.Request) (int, *tokenauth.Claims, error) {
	ret := _m.Called(req)

	var r0 int
	if rf, ok := ret.Get(0).(func(*http.Request) int); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 *tokenauth.Claims
	if rf, ok := ret.Get(1).(func(*http.Request) *tokenauth.Claims); ok {
		r1 = rf(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*tokenauth.Claims)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*http.Request) error); ok {
		r2 = rf(req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
