required:
  - id
  - name
  - multi_tenant
  - admin
  - code
type: object
properties:
  id:
    readOnly: true
    type: string
  name:
    type: string
  multi_tenant:
    type: boolean
  admin:
    type: boolean
  code:
    type: string
  types:
    type: array
    items:
      $ref: "./ApplicationType.yaml"