type: object
properties:
  default:
    oneOf:
      - $ref: "./LoginSessionSettings.yaml"
      - $ref: "./AuthConfigOidc.yaml"
  overrides:
    type: array
    items:
      oneOf:
        - $ref: "./LoginSessionSettings.yaml"
        - $ref: "./AuthConfigOidc.yaml"