required:
  - id
  - name
  - multi_tenant
  - admin
  - shared_identities
type: object
properties:
  id:
    readOnly: true
    type: string
  name:
    type: string
  multi_tenant:
    type: boolean
  admin:
    type: boolean
  shared_identities:
    type: boolean
  types:
    type: array
    items:
      $ref: "./ApplicationType.yaml"