type: object
properties:
  fields:
     $ref: "./ApplicationGroupFields.yaml"
  application:
    $ref: "./Application.yaml"
  permissions:
    type: array
    items:
      $ref: "./Permission.yaml"
  roles:
    type: array
    items:
      $ref: "./ApplicationRole.yaml"