required:
  - identity_provider_id
  - user_identifier_field
type: object
properties:
  identity_provider_id:
    type: string
  user_identifier_field:
    type: string
  external_id_fields: # map
    type: object
    additionalProperties:
      type: string
    nullable: true
  first_name_field:
    type: string
  middle_name_field:
    type: string
  last_name_field:
    type: string
  email_field:
    type: string
  ferpa_field:
    type: string
  roles_field:
    type: string
  groups_field:
    type: string
  user_specific_fields:
    type: array
    items:
      type: string
    nullable: true
  roles:
    type: object
    additionalProperties:
      type: string
    nullable: true
  groups:
    type: object
    additionalProperties:
      type: string
    nullable: true
  always_sync_profile:
    type: boolean 
  identity_bb_base_url:
    type: string
  admin_app_access_roles:
    type: array
    items:
      type: string