type: object
properties:
  max_concurrent_sessions:
    type: integer
  access_token_expiration_policy:
    $ref: "./AccessTokenExpirationPolicy.yaml"
  inactivity_expire_policy:
    $ref: "./InactiveExpirePolicy.yaml"
  time_since_login_expire_policy:
    $ref: "./TSLExpirePolicy.yaml"
  yearly_expire_policy:
    $ref: "./YearlyExpirePolicy.yaml"