required:
  - id
  - domains
type: object
properties:
  id:
    readOnly: true
    type: string
    description: organization config id
  domains:
    type: array
    description: organization domains
    items:
      type: string