get:
  tags:
  - System
  summary: Get application API keys
  description: |
    Returns all API key records for a given app ID

    **Auth:** Requires system access token with `get_api-keys` or `all_api-keys` permission
  security:
    - bearerAuth: []
  parameters:
    - name: app_id
      in: query
      description: The app ID of the API keys to return
      required: true
      style: form
      explode: false
      schema:
        type: string
  responses:
    200:
      description: Success
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../schemas/auth/APIKey.yaml'
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error