 get:
  tags:
  - System
  summary: Get applications
  description: |
    Gets applications
  
    **Auth:** Requires system access token with `get_applications`, `udpate_applications`, or `all_applications` permission
  security:
    - bearerAuth: []
  responses:
      200:
        description: Successful operation
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "../../schemas/application/Application.yaml"
      400:
        description: Bad request
      401:
        description: Unauthorized
      500:
        description: Internal error
 post:
  tags:
  - System
  summary: Create application
  description: |
    Creates application

    **Auth:** Requires system access token with `update_applications` or `all_applications` permission
  security:
    - bearerAuth: []
  requestBody:
    description: creates one application
    content:
      application/json:
        schema:
         $ref: "../../schemas/apis/system/create-application/request/Request.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error