get:
  tags:
  - System
  summary: Get application by ID
  description: |
    Gets application by provided ID

    **Auth:** Requires system access token with `get_applications` or `all_applications` permission
  security:
    - bearerAuth: []
  parameters:
  - name: id
    in: path
    description: ID of the application
    required: true
    style: simple
    explode: false
    schema:
      type: string
  responses:
    200:
      description: successful operation
      content:
        application/json:
            schema:
              $ref: "../../schemas/application/Application.yaml"
    400:
      description: Bad request
    401:
      description: Unauthorized
    404:
      description: Not Found
    500:
      description: Internal error
