get:
  tags:
  - System
  summary: Get app-org
  description: |
    Get app-org by ID

    **Auth:** Requires system access token with `get_app_orgs` or `all_app_orgs` permission
  security:
    - bearerAuth: []
  parameters:
  - name: id
    in: path
    description: ID of the app-org to retrieve
    required: true
    style: simple
    explode: false
    schema:
      type: string
  responses:
    200:
      description: Success
      content:
        application/json:
          schema:
            $ref: "../../schemas/application/AppOrg.yaml"
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error
put:
  tags:
  - System
  summary: Update app-org by ID
  description: |
    Updates app-org by ID

    **Auth:** Requires system access token with `update_app_orgs` or `all_app_orgs` permission
  security:
    - bearerAuth: []
  parameters:
  - name: id
    in: path
    description: ID of the app-org that needs to be updated
    required: true
    style: simple
    explode: false
    schema:
      type: string
  requestBody:
    description: update one app-org
    content:
      application/json:
        schema:
          $ref: "../../schemas/application/AppOrg.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error