get:
  tags:
  - System
  summary: Get application
  description: |
    Gets application

    **Auth:** Requires auth token with `app_admin` permission
  security:
    - bearerAuth: []
  parameters:
  - name: id
    in: path
    description: ID of the application
    required: true
    style: simple
    explode: false
    schema:
      type: string
  responses:
    200:
      description: successful operation
      content:
        application/json:
            schema:
              $ref: "../../schemas/apis/system/get-application/request/Request.yaml"
    400:
      description: Bad request
    401:
      description: Unauthorized
    404:
      description: Not Found
    500:
      description: Internal error
