get:
  tags:
  - System
  summary: Get config
  description: |
    Gives the system global config

    **Auth:** Requires system access token with `get_global-config`, `update_global-config`, or `all_global-config` permission
  security:
    - bearerAuth: []
  parameters:
    - name: id
      in: path
      description: config ID
      required: true
      style: simple
      explode: false
      schema:
        type: string
  responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              $ref: "../../schemas/config/Config.yaml"
      400:
        description: Bad request
      401:
        description: Unauthorized
      500:
        description: Internal error
post:
  tags:
  - System
  summary: Create global config
  description: |
    Creates the system global config

    **Auth:** Requires system access token with `update_global-config` or `all_global-config` permission
  security:
    - bearerAuth: []
  parameters:
    - name: id
      in: path
      description: config ID
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../schemas/config/Config.yaml"
    required: true
  responses:
      200:
        description: Success
        content:
          text/plain:
            schema:
              type: string
              example: Success
      400:
        description: Bad request
      401:
        description: Unauthorized
      500:
        description: Internal error
put:
  tags:
  - System
  summary: Update global config
  description: |
    Updates the system global config

    **Auth:** Requires system access token with `update_global-config` or `all_global-config` permission
  security:
    - bearerAuth: []
  parameters:
    - name: id
      in: path
      description: config ID
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../schemas/config/Config.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error