type: object
properties:
    description: organization config id
  domains:
    type: array
    description: organization domains
    items:
      type: string
  config:
     $ref: "../../admin/OrganizationConfig.yaml"