// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	logs "github.com/rokwire/logging-library-go/logs"
	mock "github.com/stretchr/testify/mock"

	model "core-building-block/core/model"
)

// externalAuthType is an autogenerated mock type for the externalAuthType type
type externalAuthType struct {
	mock.Mock
}

// externalLogin provides a mock function with given fields: authType, appType, appOrg, creds, params, l
func (_m *externalAuthType) externalLogin(authType model.AuthType, appType model.ApplicationType, appOrg model.ApplicationOrganization, creds string, params string, l *logs.Log) (*model.ExternalSystemUser, map[string]interface{}, error) {
	ret := _m.Called(authType, appType, appOrg, creds, params, l)

	var r0 *model.ExternalSystemUser
	if rf, ok := ret.Get(0).(func(model.AuthType, model.ApplicationType, model.ApplicationOrganization, string, string, *logs.Log) *model.ExternalSystemUser); ok {
		r0 = rf(authType, appType, appOrg, creds, params, l)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExternalSystemUser)
		}
	}

	var r1 map[string]interface{}
	if rf, ok := ret.Get(1).(func(model.AuthType, model.ApplicationType, model.ApplicationOrganization, string, string, *logs.Log) map[string]interface{}); ok {
		r1 = rf(authType, appType, appOrg, creds, params, l)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]interface{})
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(model.AuthType, model.ApplicationType, model.ApplicationOrganization, string, string, *logs.Log) error); ok {
		r2 = rf(authType, appType, appOrg, creds, params, l)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// getLoginURL provides a mock function with given fields: authType, appType, appOrg, redirectURI, l
func (_m *externalAuthType) getLoginURL(authType model.AuthType, appType model.ApplicationType, appOrg model.ApplicationOrganization, redirectURI string, l *logs.Log) (string, map[string]interface{}, error) {
	ret := _m.Called(authType, appType, appOrg, redirectURI, l)

	var r0 string
	if rf, ok := ret.Get(0).(func(model.AuthType, model.ApplicationType, model.ApplicationOrganization, string, *logs.Log) string); ok {
		r0 = rf(authType, appType, appOrg, redirectURI, l)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 map[string]interface{}
	if rf, ok := ret.Get(1).(func(model.AuthType, model.ApplicationType, model.ApplicationOrganization, string, *logs.Log) map[string]interface{}); ok {
		r1 = rf(authType, appType, appOrg, redirectURI, l)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]interface{})
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(model.AuthType, model.ApplicationType, model.ApplicationOrganization, string, *logs.Log) error); ok {
		r2 = rf(authType, appType, appOrg, redirectURI, l)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// refresh provides a mock function with given fields: params, authType, appType, appOrg, l
func (_m *externalAuthType) refresh(params map[string]interface{}, authType model.AuthType, appType model.ApplicationType, appOrg model.ApplicationOrganization, l *logs.Log) (*model.ExternalSystemUser, map[string]interface{}, error) {
	ret := _m.Called(params, authType, appType, appOrg, l)

	var r0 *model.ExternalSystemUser
	if rf, ok := ret.Get(0).(func(map[string]interface{}, model.AuthType, model.ApplicationType, model.ApplicationOrganization, *logs.Log) *model.ExternalSystemUser); ok {
		r0 = rf(params, authType, appType, appOrg, l)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExternalSystemUser)
		}
	}

	var r1 map[string]interface{}
	if rf, ok := ret.Get(1).(func(map[string]interface{}, model.AuthType, model.ApplicationType, model.ApplicationOrganization, *logs.Log) map[string]interface{}); ok {
		r1 = rf(params, authType, appType, appOrg, l)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]interface{})
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(map[string]interface{}, model.AuthType, model.ApplicationType, model.ApplicationOrganization, *logs.Log) error); ok {
		r2 = rf(params, authType, appType, appOrg, l)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
