post:
  tags:
  - Admin
  summary: Create application permission
  description: |
    Creates application permission
  requestBody:
    description: Application permission
    content:
      application/json:
        schema:
          $ref: "../../schemas/apis/admin/application-permissions/request/Request.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error