post:
  tags:
  - Admin
  summary: Create application role
  description: |
    Creates application role

    **Auth:** Requires auth token with `auth_admin` permission
  security:
    - bearerAuth: []
  requestBody:
    description: Application role
    content:
      application/json:
        schema:
          $ref: "../../schemas/apis/admin/application-roles/request/Request.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error