get:
  tags:
  - Admin
  summary: Get config
  description: |
    Get an existing config

    **Auth:** Requires admin access token with `get_core_configs`, `update_core_configs`, or `all_core_configs` permission
  security:
    - bearerAuth: []
  parameters:
    - name: id
      in: path
      description: config ID
      required: true
      style: simple
      explode: false
      schema:
        type: string
  responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              $ref: "../../schemas/config/Config.yaml"
      400:
        description: Bad request
      401:
        description: Unauthorized
      500:
        description: Internal error
put:
  tags:
  - Admin
  summary: Update config
  description: |
    Updates an existing config

    **Auth:** Requires admin access token with `update_core_configs` or `all_core_configs` permission
  security:
    - bearerAuth: []
  parameters:
    - name: id
      in: path
      description: config ID
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../schemas/config/Config.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error
delete:
  tags:
  - Admin
  summary: Delete config
  description: |
    Deletes a config

    **Auth:** Requires admin access token with `delete_core_configs` or `all_core_configs` permission
  security:
    - bearerAuth: []
  parameters:
    - name: id
      in: path
      description: config ID
      required: true
      style: simple
      explode: false
      schema:
        type: string
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error