get:
  tags:
  - Admin
  summary: Get configs
  description: |
    Get existing configs by search parameters

    **Auth:** Requires admin access token with `get_core_configs`, `update_core_configs`, or `all_core_configs` permission
  security:
    - bearerAuth: []
  parameters:
    - name: type
      in: query
      description: config type
      required: false
      style: form
      explode: false
      schema:
        type: string
    - name: all_apps
      in: query
      description: whether to search for configs used across apps for claimed org
      required: false
      style: form
      explode: false
      schema:
        type: boolean
    - name: all_orgs
      in: query
      description: whether to search for configs used across orgs for claimed app
      required: false
      style: form
      explode: false
      schema:
        type: boolean
  responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "../../schemas/config/Config.yaml"
      400:
        description: Bad request
      401:
        description: Unauthorized
      500:
        description: Internal error
post:
  tags:
  - Admin
  summary: Create config
  description: |
    Creates a new config

    **Auth:** Requires admin access token with `update_core_configs` or `all_core_configs` permission
  security:
    - bearerAuth: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../schemas/config/Config.yaml"
    required: true
  responses:
      200:
        description: Success
        content:
          text/plain:
            schema:
              type: string
              example: Success
      400:
        description: Bad request
      401:
        description: Unauthorized
      500:
        description: Internal error
