required:
  - id
  - data
  - date_created
  - date_updated
type: object
properties:
  id:
    readOnly: true
    type: string
  data:
    anyOf:
      - $ref: "./EnvConfigData.yaml"
  date_created:
    readOnly: true
    type: string
  date_updated:
    readOnly: true
    type: string