type: object
properties:
  allow_legacy_refresh:
    type: boolean
    nullable: true
  cors_allowed_origins:
    type: array
    items:
      type: string
    nullable: true
  cors_allowed_headers:
    type: array
    items:
      type: string
    nullable: true