openapi: 3.0.3
info:
  title: Rokwire Core Building Block API
  description: Core Building Block API Documentation
  version: 1.0.0
servers:
- url: https://api.rokwire.illinois.edu
  description: Production server
- url: https://api-test.rokwire.illinois.edu
  description: Test server
- url: https://api-dev.rokwire.illinois.edu
  description: Development server
tags:
- name: Auth
  description: APIs handling the authentication.
- name: Common
  description: End users applications APIs.
- name: Admin
  description: Administration applications APIs.
- name: Enc
  description: APIs consumed by the Encryption building block.
- name: BBs
  description: APIs consumed by the platform building blocks.
components:
  schemas:
    Organization:
      required:
        - id
        - name
        - type
      type: object
      properties:
        id:
          type: string
          description: the organization id
        name:
        type: string
        description: TODO
        otype:
          type: string
          enum:
            - V1
            - V2
            - Other
          description: TODO
        requires-own-login:
          type: boolean
          description: TODO
        login-types:
          type: array
          description: TODO
          items:
            type: string
        config:
          $ref: "#/components/schemas/OrganizationConfig"
          description: TODO
    OrganizationConfig:
      type: object
      properties:
        id:
          type: string
          description: the organization config id
        domains:
          type: array
          description: organization domains
          items:
            type: string
        