openapi: 3.0.3
info:
  title: Rokwire Core Building Block API
  description: Core Building Block API Documentation
  version: 1.0.0
servers:
- url: https://api.rokwire.illinois.edu
  description: Production server
- url: https://api-test.rokwire.illinois.edu
  description: Test server
- url: https://api-dev.rokwire.illinois.edu
  description: Development server
tags:
- name: Auth
  description: Bla bla.
- name: Common
  description: Bla bla.
- name: Admin
  description: Bla bla.
- name: Enc
  description: Bla bla.
- name: BBs
  description: Bla bla.