post:
  tags:
  - Default
  summary: Update app configs from github webhooks
  description: |
    Handle github webhook requests

    **Auth:** Requires GitHub webhook serect token
  requestBody:
    description: App configs file updated on github
    content:
      application/json:
        schema:
          $ref: "../../schemas/apis/default/request/WebhookRequest.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error