openapi: 3.0.3
info:
  title: Rokwire Core Building Block API
  description: Core Building Block API Documentation
  version: 1.0.0
servers:
- url: https://api.rokwire.illinois.edu/core
  description: Production server
- url: https://api-test.rokwire.illinois.edu/core
  description: Test server
- url: https://api-dev.rokwire.illinois.edu/core
  description: Development server
- url: http://localhost/core
  description: Local server
tags:
- name: Auth
  description: APIs handling the authentication.
- name: Common
  description: End users applications APIs.
- name: Admin
  description: Administration applications APIs.
- name: Enc
  description: APIs consumed by the Encryption building block.
- name: BBs
  description: APIs consumed by the platform building blocks.
paths:
  /version:
    get:
      summary: Get service version
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: v1.1.0
  /admin/global-config:
    get:
      tags:
      - Admin
      summary: Get global config
      description: |
        Gives the system global config
      responses:
          200:
            description: Successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/GlobalConfig'
          400:
            description: Bad request
          401:
            description: Unauthorized
          500:
            description: Internal error
    post:
      tags:
      - Admin
      summary: Create global config
      description: |
        Creates the system global config
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GlobalConfig'
        required: true
      responses:
          200:
            description: successful operation
            content:
              text/plain:
                schema:
                  type: string
                  example: Successfully created
          400:
            description: Bad request
          401:
            description: Unauthorized
          500:
            description: Internal error
    put:
      tags:
      - Admin
      summary: Update global config
      description: |
        Updates the system global config
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GlobalConfig'
        required: true
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: Successfully updated
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal error
  /admin/organizations/{id}:
    put:
      tags:
      - Admin
      summary: Update organization
      description: |
        Updates organization
      parameters:
      - name: id
        in: path
        description: ID of the organization that needs to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: update one organization
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
        required: true
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: Successfullly created
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal error
  /admin/organizations:
    post:
      tags:
      - Admin
      summary: Create organization
      description: |
        Creates organization
      requestBody:
        description: creates one organization
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
        required: true
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: Successfullly created
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal error
  /enc/test:
    $ref: "./resources/enc/test.yaml"
components:
  schemas:
    $ref: "./schemas/_index.yaml"