openapi: 3.0.3
info:
  title: Rokwire Core Building Block API
  description: Core Building Block API Documentation
  version: 1.12.0
servers:
  - url: https://api.rokwire.illinois.edu/core
    description: Production server
  - url: https://api-test.rokwire.illinois.edu/core
    description: Test server
  - url: https://api-dev.rokwire.illinois.edu/core
    description: Development server
  - url: http://localhost/core
    description: Local server
tags:
  - name: Services
    description: Clients applications APIs.
  - name: Admin
    description: Clients administration applications APIs.
  - name: Enc
    description: APIs consumed by the Encryption building block.
  - name: BBs
    description: APIs consumed by the platform building blocks.
  - name: Third-Party Services
    description: APIs consumed by third-party services.
  - name: System
    description: System APIs.
paths:
  #services
  /services/auth/login:
    $ref: "./resources/services/auth/login.yaml"
  /services/auth/refresh:
    $ref: "./resources/services/auth/refresh.yaml"
  /services/auth/login-url:
    $ref: "./resources/services/auth/login-url.yaml"
  /services/auth/credential/verify:
    $ref: "./resources/services/auth/credential/verify.yaml"
  /services/auth/credential/send-verify:
    $ref: "./resources/services/auth/credential/send-verify.yaml"
  /services/auth/credential/forgot/initiate:
    $ref: "./resources/services/auth/credential/forgot/initiate.yaml"
  /services/auth/credential/forgot/complete:
    $ref: "./resources/services/auth/credential/forgot/complete.yaml"
  /services/auth/credential/update:
    $ref: "./resources/services/auth/credential/update.yaml"
  /services/auth/account-exists:
    $ref: "./resources/services/auth/account-exists.yaml"
  /services/auth/authorize-service:
    $ref: "./resources/services/auth/authorize-service.yaml"
  /services/auth/service-regs:
    $ref: "./resources/services/auth/service-regs.yaml"
  /services/account:
    $ref: "./resources/services/accounts/account.yaml"
  /services/account/preferences:
    $ref: "./resources/services/accounts/preferences.yaml"
  /services/account/profile:
    $ref: "./resources/services/accounts/profile.yaml"
  /services/test:
    $ref: "./resources/services/test.yaml"

  #admin
  /admin/auth/login:
    $ref: "./resources/admin/auth/login.yaml"
  /admin/auth/refresh:
    $ref: "./resources/admin/auth/refresh.yaml"
  /admin/auth/login-url:
    $ref: "./resources/admin/auth/login-url.yaml"

  #enc
  /enc/test:
    $ref: "./resources/enc/test.yaml"

  #bbs
  /bbs/test:
    $ref: "./resources/bbs/test.yaml"
  /bbs/service-regs:
    $ref: "./resources/bbs/service-regs.yaml"

  #third-party services
  /tps/service-regs:
    $ref: "./resources/third-party-services/service-regs.yaml"
  /tps/auth-keys:
    $ref: "./resources/third-party-services/auth-keys.yaml"

  #system
  /system/global-config:
    $ref: "./resources/system/global-config.yaml"
  /system/organizations/{id}:
    $ref: "./resources/system/organizationsId.yaml"
  /system/organizations:
    $ref: "./resources/system/organizations.yaml"
  /system/service-regs:
    $ref: "./resources/system/service-regs.yaml"
  /system/applications/{id}:
    $ref: "./resources/system/applicationsId.yaml"
  /system/applications:
    $ref: "./resources/system/applications.yaml"
  /system/permissions:
    $ref: "./resources/system/permissions.yaml"
  /system/application-roles:
    $ref: "./resources/system/application-roles.yaml"
  /system/application-api-keys:
    $ref: "./resources/system/application-api-keys.yaml"
  /system/account/permissions:
    $ref: "./resources/system/account/permissions.yaml"
  /system/account/roles:
    $ref: "./resources/system/account/roles.yaml"
  /system/api-keys:
    $ref: "./resources/system/api-keys.yaml"

  #default
  /version:
    $ref: "./resources/default/version.yaml"
  /.well-known/openid-configuration:
    $ref: "./resources/default/openid-configuration.yaml"
components:
  securitySchemes:
      bearerAuth:            # arbitrary name for the security scheme
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    $ref: "./schemas/index.yaml"
