get:
  tags:
  - Admin
  summary: Get system configs
  description: |
    Returns account system configs

    **Auth:** Requires admin access token with `get_account-system-configs` or `all_account-system-configs` permission
  security:
    - bearerAuth: []
  parameters:
    - name: id
      in: path
      description: The account ID
      required: true
      style: simple
      explode: false
      schema:
        type: string
  responses:
     200:
      description: Success
      content:
        application/json:
          schema: 
            type: object
            nullable: true
     400:
      description: Bad request
     401:
      description: Unauthorized
     500:
      description: Internal error
put:
  tags:
    - Admin
  summary: Update account system configs
  description: |
    Updates account system configs

    **Auth:** Requires admin access token with `update_account-system-configs` or `all_account-system-configs` permission
  security:
    - bearerAuth: []
  parameters:
    - name: id
      in: path
      description: The account ID
      required: true
      style: simple
      explode: false
      schema:
        type: string
    - name: create-anonymous
      in: query
      description: Create anonymous account if account with ID cannot be found. Default is `false`
      required: false
      style: form
      explode: false
      schema:
        type: boolean
  requestBody:
    description: Account system configs (will be merged with existing configs)
    content:
      application/json:
        schema: 
          type: object
    required: true
  responses:
    '200':
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    '400':
      description: Bad request
    '401':
      description: Unauthorized
    '500':
      description: Internal error