// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Administration is an autogenerated mock type for the Administration type
type Administration struct {
	mock.Mock
}

// AdmGetTest provides a mock function with given fields:
func (_m *Administration) AdmGetTest() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AdmGetTestModel provides a mock function with given fields:
func (_m *Administration) AdmGetTestModel() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
