// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ApplicationListener is an autogenerated mock type for the ApplicationListener type
type ApplicationListener struct {
	mock.Mock
}
