// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ApplicationListener is an autogenerated mock type for the ApplicationListener type
type ApplicationListener struct {
	mock.Mock
}
