// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "core-building-block/core/model"

	mock "github.com/stretchr/testify/mock"

	mongo "go.mongodb.org/mongo-driver/mongo"

	storage "core-building-block/driven/storage"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// CreateGlobalConfig provides a mock function with given fields: sessionContext, globalConfig
func (_m *Storage) CreateGlobalConfig(sessionContext mongo.SessionContext, globalConfig *model.GlobalConfig) error {
	ret := _m.Called(sessionContext, globalConfig)

	var r0 error
	if rf, ok := ret.Get(0).(func(mongo.SessionContext, *model.GlobalConfig) error); ok {
		r0 = rf(sessionContext, globalConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAccount provides a mock function with given fields: sessionContext, id
func (_m *Storage) DeleteAccount(sessionContext mongo.SessionContext, id string) error {
	ret := _m.Called(sessionContext, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(mongo.SessionContext, string) error); ok {
		r0 = rf(sessionContext, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteApplicationGroup provides a mock function with given fields: id
func (_m *Storage) DeleteApplicationGroup(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteApplicationRole provides a mock function with given fields: id
func (_m *Storage) DeleteApplicationRole(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDevice provides a mock function with given fields: sessionContext, id
func (_m *Storage) DeleteDevice(sessionContext mongo.SessionContext, id string) error {
	ret := _m.Called(sessionContext, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(mongo.SessionContext, string) error); ok {
		r0 = rf(sessionContext, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteGlobalConfig provides a mock function with given fields: sessionContext
func (_m *Storage) DeleteGlobalConfig(sessionContext mongo.SessionContext) error {
	ret := _m.Called(sessionContext)

	var r0 error
	if rf, ok := ret.Get(0).(func(mongo.SessionContext) error); ok {
		r0 = rf(sessionContext)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePermission provides a mock function with given fields: id
func (_m *Storage) DeletePermission(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAccountByID provides a mock function with given fields: sessionContext, id
func (_m *Storage) FindAccountByID(sessionContext mongo.SessionContext, id string) (*model.Account, error) {
	ret := _m.Called(sessionContext, id)

	var r0 *model.Account
	if rf, ok := ret.Get(0).(func(mongo.SessionContext, string) *model.Account); ok {
		r0 = rf(sessionContext, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(mongo.SessionContext, string) error); ok {
		r1 = rf(sessionContext, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindApplication provides a mock function with given fields: ID
func (_m *Storage) FindApplication(ID string) (*model.Application, error) {
	ret := _m.Called(ID)

	var r0 *model.Application
	if rf, ok := ret.Get(0).(func(string) *model.Application); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Application)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindApplicationRoles provides a mock function with given fields: ids, appID
func (_m *Storage) FindApplicationRoles(ids []string, appID string) ([]model.ApplicationRole, error) {
	ret := _m.Called(ids, appID)

	var r0 []model.ApplicationRole
	if rf, ok := ret.Get(0).(func([]string, string) []model.ApplicationRole); ok {
		r0 = rf(ids, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ApplicationRole)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, string) error); ok {
		r1 = rf(ids, appID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindApplications provides a mock function with given fields:
func (_m *Storage) FindApplications() ([]model.Application, error) {
	ret := _m.Called()

	var r0 []model.Application
	if rf, ok := ret.Get(0).(func() []model.Application); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Application)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOrganization provides a mock function with given fields: id
func (_m *Storage) FindOrganization(id string) (*model.Organization, error) {
	ret := _m.Called(id)

	var r0 *model.Organization
	if rf, ok := ret.Get(0).(func(string) *model.Organization); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Organization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPermissionsByName provides a mock function with given fields: names
func (_m *Storage) FindPermissionsByName(names []string) ([]model.Permission, error) {
	ret := _m.Called(names)

	var r0 []model.Permission
	if rf, ok := ret.Get(0).(func([]string) []model.Permission); ok {
		r0 = rf(names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Permission)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(names)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGlobalConfig provides a mock function with given fields:
func (_m *Storage) GetGlobalConfig() (*model.GlobalConfig, error) {
	ret := _m.Called()

	var r0 *model.GlobalConfig
	if rf, ok := ret.Get(0).(func() *model.GlobalConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GlobalConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertAccountPermissions provides a mock function with given fields: accountID, permissions
func (_m *Storage) InsertAccountPermissions(accountID string, permissions []model.Permission) error {
	ret := _m.Called(accountID, permissions)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []model.Permission) error); ok {
		r0 = rf(accountID, permissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertAccountRoles provides a mock function with given fields: accountID, appID, roles
func (_m *Storage) InsertAccountRoles(accountID string, appID string, roles []model.ApplicationRole) error {
	ret := _m.Called(accountID, appID, roles)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []model.ApplicationRole) error); ok {
		r0 = rf(accountID, appID, roles)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertApplication provides a mock function with given fields: application
func (_m *Storage) InsertApplication(application model.Application) (*model.Application, error) {
	ret := _m.Called(application)

	var r0 *model.Application
	if rf, ok := ret.Get(0).(func(model.Application) *model.Application); ok {
		r0 = rf(application)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Application)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Application) error); ok {
		r1 = rf(application)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertApplicationGroup provides a mock function with given fields: item
func (_m *Storage) InsertApplicationGroup(item model.ApplicationGroup) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.ApplicationGroup) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertApplicationRole provides a mock function with given fields: item
func (_m *Storage) InsertApplicationRole(item model.ApplicationRole) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.ApplicationRole) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertOrganization provides a mock function with given fields: organization
func (_m *Storage) InsertOrganization(organization model.Organization) (*model.Organization, error) {
	ret := _m.Called(organization)

	var r0 *model.Organization
	if rf, ok := ret.Get(0).(func(model.Organization) *model.Organization); ok {
		r0 = rf(organization)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Organization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Organization) error); ok {
		r1 = rf(organization)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertPermission provides a mock function with given fields: item
func (_m *Storage) InsertPermission(item model.Permission) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Permission) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadApplications provides a mock function with given fields:
func (_m *Storage) LoadApplications() ([]model.Application, error) {
	ret := _m.Called()

	var r0 []model.Application
	if rf, ok := ret.Get(0).(func() []model.Application); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Application)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadOrganizations provides a mock function with given fields:
func (_m *Storage) LoadOrganizations() ([]model.Organization, error) {
	ret := _m.Called()

	var r0 []model.Organization
	if rf, ok := ret.Get(0).(func() []model.Organization); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Organization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PerformTransaction provides a mock function with given fields: _a0
func (_m *Storage) PerformTransaction(_a0 func(mongo.SessionContext) error) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(mongo.SessionContext) error) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterStorageListener provides a mock function with given fields: storageListener
func (_m *Storage) RegisterStorageListener(storageListener storage.Listener) {
	_m.Called(storageListener)
}

// SaveDevice provides a mock function with given fields: sessionContext, device
func (_m *Storage) SaveDevice(sessionContext mongo.SessionContext, device *model.Device) error {
	ret := _m.Called(sessionContext, device)

	var r0 error
	if rf, ok := ret.Get(0).(func(mongo.SessionContext, *model.Device) error); ok {
		r0 = rf(sessionContext, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAccountPreferences provides a mock function with given fields: accountID, preferences
func (_m *Storage) UpdateAccountPreferences(accountID string, preferences map[string]interface{}) error {
	ret := _m.Called(accountID, preferences)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(accountID, preferences)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateApplicationGroup provides a mock function with given fields: item
func (_m *Storage) UpdateApplicationGroup(item model.ApplicationGroup) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.ApplicationGroup) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateApplicationRole provides a mock function with given fields: item
func (_m *Storage) UpdateApplicationRole(item model.ApplicationRole) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.ApplicationRole) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOrganization provides a mock function with given fields: ID, name, requestType, organizationDomains
func (_m *Storage) UpdateOrganization(ID string, name string, requestType string, organizationDomains []string) error {
	ret := _m.Called(ID, name, requestType, organizationDomains)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, []string) error); ok {
		r0 = rf(ID, name, requestType, organizationDomains)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePermission provides a mock function with given fields: item
func (_m *Storage) UpdatePermission(item model.Permission) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Permission) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProfile provides a mock function with given fields: accountID, profile
func (_m *Storage) UpdateProfile(accountID string, profile *model.Profile) error {
	ret := _m.Called(accountID, profile)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *model.Profile) error); ok {
		r0 = rf(accountID, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
