// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	logs "github.com/rokwire/logging-library-go/logs"
	mock "github.com/stretchr/testify/mock"

	model "core-building-block/core/model"
)

// ProfileBuildingBlock is an autogenerated mock type for the ProfileBuildingBlock type
type ProfileBuildingBlock struct {
	mock.Mock
}

// GetProfileBBData provides a mock function with given fields: queryParams, l
func (_m *ProfileBuildingBlock) GetProfileBBData(queryParams map[string]string, l *logs.Log) (*model.Profile, map[string]interface{}, error) {
	ret := _m.Called(queryParams, l)

	var r0 *model.Profile
	if rf, ok := ret.Get(0).(func(map[string]string, *logs.Log) *model.Profile); ok {
		r0 = rf(queryParams, l)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Profile)
		}
	}

	var r1 map[string]interface{}
	if rf, ok := ret.Get(1).(func(map[string]string, *logs.Log) map[string]interface{}); ok {
		r1 = rf(queryParams, l)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]interface{})
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(map[string]string, *logs.Log) error); ok {
		r2 = rf(queryParams, l)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
