required:
  - host
  - redirect_uri
  - client_id
  - client_secret
type: object
properties:
  app_type_id:
    type: string
    nullable: true
  host:
    type: string
  authorize_url:
    type: string
  token_url:
    type: string
  userinfo_url:
    type: string
  scopes:
    type: string
  allow_signup:
    type: boolean
  use_refresh:
    type: boolean
  use_state:
    type: boolean
  client_id:
    type: string
  client_secret:
    type: string